### ISSUE TITLE
GSoD merging list - Dynamic

### ISSUE THREAD

**Issue by Rohitesh-Kumar-Jain** [wechaty/docusaurus#1056]
References section PR

| PR  | Status | Rui | Huan |
| --- | ------ | --- | ---- |

Introduction and explanation PRs

| PR   | Status | Rui                          | Huan |
| ---- | ------ | ---------------------------- | ---- |

Tutorials PRs
| PR | Status | Rui | Huan |
| ---------------- | ------ | -------------- | ---- |

How to guides PRs

| PR    | Status | Rui                          | Huan |
| ----- | ------ | ---------------------------- | ---- |
| #1139 | open   | Change Request :exclamation: |      |

**Comment by Rohitesh-Kumar-Jain** [comment]
I think it's better if volunteers have the access to merge simple PRs like #870.

**Comment by lijiarui** [comment]
Thanks for @Rohitesh-Kumar-Jain clear change！

**Comment by Rohitesh-Kumar-Jain** [comment]
I think we no longer need this issue, as now virtually all the PRs tagged with "GSoD" are eligible for this list, and have received at least one review from mentors. So I am closing this issue, feel free to reopen this again, if anyone feels that we still need this issue.
