### ISSUE TITLE
invite @Jesse to write a blog about his eleme red envelope bot

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#107]
[Jesse](https://github.com/JesseWeb) is an interesting full stack developer, living in Shenzhen. He likes to write bots to solve the problem in our life.

He just made a bot for [eleme](https://www.ele.me/) red pocket. When you share your eleme-red-envelope-link to the bot, he will get the red-envelope until the previous one of the largest envelope. At the same time, bot tells you if you open this red-envelope-link at this time, you will get the largest red envelope.

It's an interesting case using wechaty, so I 'd like to invite Jesse to write a blog about this.

We are looking forward to your article, @JesseWeb, cheers!

**Comment by lijiarui** [comment]
Just now, @Jesse said he was damn busy about his job & life, so this blog may be finished at the middle of Nov.

Looking forward to the blog！

Thanks！

**Comment by lijiarui** [comment]
ping @jesse ：）

**Comment by huan** [comment]
I'm going to close this issue because it had delayed too long.

Please let me know by leaving a reply if you want to write it and I would like to reopen it for you.
