### ISSUE TITLE
invite @basicthinker & @UltimateBeaver to write a blog to analysis the contribution of the Wechaty project

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#109]
@basicthinker is the co-founder & CEO of Merico, Reacher of MSRA, @UltimateBeaver is the co-founder & CTO of Merico. Merico is focusing on **Assessing the Value of Code Contributors**. This is very valuable to the open source projects because it will motivate contributors more. The members of Merico are coming from MSRA/Berkeley/Stanford.

**Comment by basicthinker** [comment]
The report is on the way. Coming soon!

Find more about our work:
- [Software Development in the Next Decade: Beyond the Dichotomy of Open-Source and Corporate Worlds](https://medium.com/p/985742ba1aee)
- [What We Talk about When We Talk about a Decentralized GitHub](https://medium.com/p/80edd708b80b)

**Comment by hezyin** [comment]
@zixia Thanks for the invite! We'll look into supporting Typescript!

**Comment by huan** [comment]
Thank you for the excellent birthday cake blog!

I had merged your draft because it's time-consuming... and looking forward to your rest part of this blog in the following days!

**Comment by huan** [comment]
Close this issue because the blog had been published.
