### ISSUE TITLE
Combine all of the contribution guide together

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1111]
As talked with @iamrajiv [https://github.com/wechaty/wechaty.js.org/pull/917](https://github.com/wechaty/wechaty.js.org/pull/917#discussion_r671872372) 

I think wechaty should have only one contributing file, it should be: http://wechaty.js.org/docs/contributing/

We should merge https://github.com/wechaty/openapi/pull/16  and https://github.com/wechaty/wechaty/blob/master/CONTRIBUTING.md to http://wechaty.js.org/docs/contributing/ together, and all of the start contributing link is the unified link: http://wechaty.js.org/docs/contributing/

I suggest [Introduction] team improves contributing page in the next period, how do you think so? @Rohitesh-Kumar-Jain

**Comment by huan** [comment]
I agree that all the CONTRIBUTING.md files in our wechaty projects' repo should be simply linked to https://wechaty.js.org/docs/contributing/ , if anyone wants to create it.

It's also acceptable to not have CONTRIBUTING.md at all, by adding a `## Contributing` section in the README.md file.
