### ISSUE TITLE
invite @ifreedom to write a blog about how to organize technology community

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#112]
@ifreedom is one of the organizers of Shanghai gdg(Google Developer Group) and organized a lot of interesting activities in Shanghai. Also, he is a technical director in a game company. 

When I come to Shanghai, we talked a lot of ideas about how to build a technology community, so I'd like to invite him to write a blog about these ideas.

Looking forward to your blog!

Thanks!

**Comment by huan** [comment]
Welcome @ifreedom and looking forward to seeing your awesome blog post!

**Comment by huan** [comment]
I'm going to close this issue because it had delayed too long.

Please let me know by leaving a reply if you want to write it and I would like to reopen it for you.
