### ISSUE TITLE
invite william to share our first WWDC in Silicon Valley!

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#114]
Last night we have a great meet up with chatie contributors at Mountview Google office.

William would like to share this great event with the community, thanks!

**Comment by kis87988** [comment]
will do.

**Comment by kis87988** [comment]
WIP

**Comment by kis87988** [comment]
# Wechaty WWDC Blog

首先，Wechaty對我來說是非常意義重大的一個Open sources Project, 也是我第一個在GitHub做Contributor的Project。

Being a software engineer, it is my pleasure to join this project and event.

做為一個Wechaty Platform的使用者跟貢獻者，Wechaty讓我們的生活更簡單
我一開始的目標是希望可以建立一個群幫助Slicon valley的De Anza College學生，但是由於Wechat的100人QR Code限制，
導致我需要使用人工的方式拉群，這是非常麻煩的，所以我開始尋找可以輕鬆簡單用非人工的方式，嘗試了很多類似的Project，
Wechaty就是唯一最好用最Powerful並且擴展性高的Wechat工具了。
我認為Wechaty之所以會這麼Powerful是因為有各路願意貢獻的偉大貢獻者們，才可以做出這麼優秀的Open source project，
個人我也希望可以從各位Contributor身上學到更多技能也希望可以互相幫助。

這篇文章因為是由有拖延症的我編寫，導致延遲了接近一年，深感抱歉，現在讓我們來坐坐時光機回去吧

讓我們回到2018年前的11月7日，在Chatie開源創始人的李董人來訪美國時，發生了神奇的事

Guess what! Something happened. 對的！就是 Chatie WWDC in Silicon Valley!!

對於小弟我，第一次參加這種盛大的宴會也是我第一次見到李董本人，我們之前都是網友，我曾經以為他就是個機器人，
這種想見面的心情又緊張又期待，當天我連要穿什麼都不知道，到底是要穿西裝打領帶，還是要穿蘇格蘭裙呢？
翻翻李董朋友圈的照片穿著，我還是決定效法一波程序猿正常的穿著打扮，就是一個Tshirt配個牛仔褲去參加拉～

因為有選擇困難症的我們，實在不知道要辦在哪，然而李董貌似又想要在有朝一日進Google當實習生。
所以當然要去參觀一下Google大本營，
巧合之下，我們有另外一位靠普的周載南小伙伴在Google工作，帶著我們參觀了Google內部及辦公室的美食

對了，忘了介紹了一下參加者名單，讓我們來介紹一下吧！

裝{}組織名單如下：

1. 李卓桓
   外號李機器人、李董、Microsoft AI MVP & Regional Director，不需要過多介紹一下，就是我們這次活動的大領導，
   無人不知無人不曉的 Chatie product owner，可能是未來  Google AI interner"。
2. 周載南
   Google程序猿，我們這次活動的靠普場地提供者，好室友(www.haoshiyou.org)項目的Product owner，
   這次也Share給我們很多有趣的Business ideas。
3. 任晶磊
   YC創投參加者之一，正在創立Code Contribution scale system(關於開源社區的福利項目之一)，
   對於正在創立的System非常有任情也跟我們解說如何做Coding analysis。
4. 林思奇
   李董的學妹，現在在Slicon valley的某間創投公司工作，非常有能力。
5. William(威廉)
   時常幫忙端茶倒水的程序猿，當時無夜遊名，現在是打工仔。

我們是一群擁有純樸又愛喝奶茶的心，而聚在一起。
當我們聚在一起聊的東西天南地北的，但事實則無題。

在Google聊了很多有關於未來Chatie的應用及發展，還有很多未來的Software開源社區創建以及管理，
我們大家也對晶磊正在做的東西非常有興趣，想要知道未來要怎麼量化Code才不會讓開源社區的Contributor的貢獻變成Pointless。
當然我們也希望我們的李董及林思奇未來在創業方面可以給我們一盞資金的明燈，讓我們可以沒有後顧之憂的寫代碼，
這會是我們非常嚮往的生活。

其間我們還聊到了如何給各大有名的trending open sources做Contribution，這是一個非常有趣的奇妙思想，
如有興趣請參詳李董，他會告訴你他是如何貢獻給Tensowflow repo的，並且載南也實踐過但是不如卓桓哥而裝{}失敗了。

就在我們天花亂墜的跳躍聊天後，當然免不了要來張大合照拉！
這時候我們的Googler發生了一件非常可愛的事情，他不知道自己家的手機產品可以語音自動Take Selfie
讓我們非常極度懷疑他是個假的Googler，但是鑑於他有個工作牌還是勉強相信了他，有圖有真相！
<圖片>

這個時光之旅也到了一個段落了，讓我們回到現實吧！

這次的WWDC之旅，是個非常有趣的體驗。歡迎大家以後多參加Chatie的活動，
這樣可以讓這個Repo更好更健壯，並且大家都有交流也有更多的Idea來貢獻給開源社區。

再次謝謝李董給我這個機會給我寫這個拖延已久的Blog、也謝謝載南哥Host我們參觀Google Mountain View office。

**Comment by lijiarui** [comment]
@kis87988 you can try to pull request to this repo, see https://github.com/chatie/blog#how-to-post-blog

**Comment by huan** [comment]
@kis87988 When could we expect this blog to be published? Will appreciate for your blogging and hope we can do it at the beginning of the year 2019 soon! :)

**Comment by huan** [comment]
ping @kis87988 

This blog should be published ASAP because there almost 8 months passed by!

**Comment by kis87988** [comment]
@huan 
Sorry for the holy moly delay. 
I will try my best to do that before Sep. 
🐢
