### ISSUE TITLE
Error in self-testing-bot

### ISSUE THREAD

**Issue by sbis04** [wechaty/docusaurus#1146]
There is a minor error in the `self-testing-bot` code on [this line](https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/self-testing-bot.js#L68), it should be:

```js
qrTerm.generate(qrcode, { small: true })
```

@huan if you can make this change there then the bot will work without any error.

**Comment by sbis04** [comment]
@huan I have fixed this error in a PR: https://github.com/wechaty/wechaty-getting-started/pull/193

**Comment by huan** [comment]
@sbis04 merged, thank you very much!

**Comment by sbis04** [comment]
Thanks @huan
