### ISSUE TITLE
Blog image crash

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1168]
![image](https://user-images.githubusercontent.com/6419514/128226777-cdc4b0ff-2ed2-4161-a64b-02cc06622920.png)

![image](https://user-images.githubusercontent.com/6419514/128226792-ee62f0af-b77c-4bd7-9f3c-e341c17928af.png)

**Comment by huan** [comment]
It's because the server was maintained by me yesterday.
