### ISSUE TITLE
Invite lhr0909 to write a blog about his project

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#117]
@lhr0909 ,  ex-Amazon Software Engineer. He returned to China in 2016 and join startups, now he runs a full remote team to help startups around the world build interesting tech products/prototypes.

He just fixed a mention bug for wechaty and wechaty-puppet-padchat, he uses wechaty for his project. He would like to share his project and his experience of RxJS. He uses RxJS to control code flow and deal with the error.

Looking forward to your blog!

**Comment by huan** [comment]
Great, looking forward to reading it!

**Comment by huan** [comment]
I'm going to close this issue because it had delayed too long.

Please let me know by leaving a reply if you want to write it and I would like to reopen it for you.
