### ISSUE TITLE
Error for Running locally in tutorial part

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1185]
https://wechaty.js.org/docs/getting-started/running-locally#2-install-dependencies

We should not use wxwork package here:
![image](https://user-images.githubusercontent.com/6419514/128710857-6bf0e53f-594a-467c-a723-55d3a39517f6.png)

See related comment: 
- https://github.com/wechaty/wechaty.js.org/pull/1076#discussion_r676180298
- https://github.com/wechaty/wechaty.js.org/pull/1076#discussion_r676180910

**Comment by sbis04** [comment]
@lijiarui I had fixed this in this PR: #1148

**Comment by Rohitesh-Kumar-Jain** [comment]
> @lijiarui I had fixed this in this PR: #1148

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/62026125/129054057-cd9623fd-65cd-410f-bada-5fed386dd7cd.png">
