### ISSUE TITLE
invite @xinbenlv to write an article about how to integrate Wechaty with HaoShiYou App

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#12]
The goal of HaoShiYou is to help Chinese students in Silicon Valley to find/rent a room with other students. @xinbenlv is working at Google, founded HaoShiYou in his spare time, developed the App, and managed many 500 people Wechat group, which is a massive work for human.

After using Wechaty, he uses a bot to help him managing all Wechat works, such as add/del people in a group, save rent/lease information from Wechat message, even OCR the screenshot to read it by the bot. And here's his Bot: https://github.com/xinbenlv/haoshiyou-bot

It would be wonderful if @xinbenlv could share his experience from his HaoShiYou project, I'm looking for your article, thanks!

**Comment by xinbenlv** [comment]
Sure

**Comment by xinbenlv** [comment]
It would be great if the view mode of markdown has code syntax highlight,
it seems not
can you check if we can add this support?
http://prose.io/#Chatie/blog/blob/master/_posts/2017-04-16-how-chatie-is-used-in-haoshiyou-project.md


Zainan Victor Zhou, 周载南
Senior Software Engineer, Tech Lead at Google
650-336-5691

**Comment by huan** [comment]
Yes, we should fix it.

It looks like what we should do exactly described at here: 
<https://yaitloutou.github.io/blog/2017/01/22/jekyll-code-highlighting/>
