### ISSUE TITLE
Invite diaozxin to write a blog about his bot 

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#121]
@diaozxin007 is a JAVA engineer in ZhiHu, he write a fantastic blog about a bot to remind him have a meal.

Looking forward for your blog! Cheers!

**Comment by lijiarui** [comment]
see https://github.com/Chatie/blog/pull/123

**Comment by huan** [comment]
You've invited 犀利豆 to Chatie! They'll be receiving an email shortly. They can also visit https://github.com/Chatie to accept the invitation.
