### ISSUE TITLE
Change the order of language display

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1215]
http://wechaty.js.org/docs/examples/basic/the-worlds-shortest-chatbot-code-in-6-lines

- We should put typescript at the first tab since wechaty main language is typescript.
- We should put open API in the last tab since openapi hasn't been published yet.

![image](https://user-images.githubusercontent.com/6419514/130272833-90f58c6f-cc16-47bc-9dbd-09219c11236a.png)

**Comment by shwetalsoni** [comment]
@lijiarui I have implemented this in #1252

**Comment by lijiarui** [comment]
Good job！
