### ISSUE TITLE
Invite @timqian to share his ideas about wewe.t9t.io

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#131]
@timqian is a full stack engineer who is practicing [transparent startup](https://blog.t9t.io/transparent-startup-experiment-2019-05-20/) from last month, which is a really cool project.

[wewe](https://wewe.t9t.io) is one product from this project, and it is really awesome: Wewe can make the WeChat group message to be public and searchable, which I believe it is quite a good idea, and I hope it can be a popular service in the future!

I'd like to invite @timqian to share his wewe idea to the bot builder community and published it to chatie blog.

We are looking forward to your great thoughts in your article, and thanks for accepting my invitation!

**Comment by timqian** [comment]
@huan I have drafted a blog post about [wewe](https://wewe.t9t.io/) in my blog

blog: https://blog.t9t.io/wewe-2019-07-04/
markdown source: https://github.com/t9tio/blog/blob/master/source/_posts/wewe.md

Do you have any suggestions for this blog? I can make some updates to make it more suitable for chatie's blog

**Comment by huan** [comment]
Hi @timqian ,

Your blog looks great!

I would like to suggest that you can talk more about the values that wewe could help your users to get. Currently you have some points, however, you can make your option more strong by talking each of them in details.

And, if you could leave more specific questions to your readers, then you could expect more thoughts from your reader.

Please feel free to create a PR to chatie blog with your blog post, I'm looking forward to publishing it to the community, and I hope your product will get better and better.

Happy MVP! :)

**Comment by timqian** [comment]
Thanks for your suggestions @huan 
You are right, the blog should focus more on the user.
And  leaving specific questions to readers is a good suggestion too, I actually have a lot 😂
I will do some updates the make a PR

**Comment by huan** [comment]
Great to hear that you agree with me, and I'm looking forward for your updates. Cheer!

**Comment by huan** [comment]
ping @timqian :)

**Comment by lijiarui** [comment]
#137
