### ISSUE TITLE
Invite @coderwhocode to share his idea about chatbot

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#134]
@coderwhocode is the founder of a fintech startup called [MugglePay](http://mugglepay.com/). He graduated from Stanford and worked as an engineer for Twitter in SF before and have a lot of interesting ideas about chatbot.

Now he use wechaty to manage [Wechat Pay](pay.weixin.qq.com) data and trying to integrate wechat pay and ali pay.

Looking forward to your blog!

Cheers!

**Comment by huan** [comment]
Thank you for your great blog article!

I had invited you to our chatie contributors team, please kindly accept it from:

> You've invited Coder Who Code to Chatie! They'll be receiving an email shortly. They can also visit https://github.com/Chatie to accept the invitation.
