### ISSUE TITLE
Try to build a wechaty-TIKTOK-puppet : Regular technical report（01/11/2021-05/11/2021）

### ISSUE THREAD

**Issue by YuSihe88** [wechaty/docusaurus#1393]
**The work completed last week includes:**
1，Solve the problem of fixed domain name: specify the subdomain name with local tunnel to achieve the purpose of Intranet penetration
2，Apply to the power of the tiktok development platform, get the necessary client secret and client key.
3，Use postman to successfully monitor the event and return the random number required by the platform

**Current problems:**
1，Tiktok can quickly resolve and return to the random number required by the platform, but it can not deploy URL successfully to webhook in the development platform.

**Current solutions:**
1，Tiktok development platform negotiations
2，Temporarily skip the event subscription and use the sandbox environment for interface call and function debugging
3， Change an intranet penetration method and try to deploy webhook again

**Next week's plan:**

1，Continue to look at the source code and learn to call the interface
2，Obtain access in the sandbox environment access_Token and client_token
3，Try to call an interface successfully

**Comment by huan** [comment]
This issue is nothing related to the Wechaty Official Website.

Closed.
