### ISSUE TITLE
Just want to change the intro. in the landing page 

### ISSUE THREAD

**Issue by hailiang-wang** [wechaty/docusaurus#1394]
Feel hornored, is that you, @huan, put me in the landing page as a voice of developers, :-) 

But it should be updated a little bit.

Previous version.
```
"Wechaty is great".
-- @Samurais, SnapLingo Director of Engineering
```

Currently.

```
"Wechaty is great, plays more and more important role in the years to come".
-- @hailiang-wang, CEO, Chatopera
```

![image](https://user-images.githubusercontent.com/3538629/141980457-aa8c6160-b6f5-48db-9724-d474655e7023.png)

**Comment by huan** [comment]
Please feel free to send a PR to fix it, thank you very much!

BTW: you are picked by our GSoD'21 landing page team! ;-)

**Comment by huan** [comment]
Close this issue because the related PR has been merged.
