### ISSUE TITLE
invite @yanboshu to write an article about how to rewrite bot using lua without chrome

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#14]
@yanboshu referred wechaty writing a bot without chrome in nginx. It can enhance performance.

**Comment by huan** [comment]
Hello @yanboshu, do you have any updated plan about this blog?

**Comment by huan** [comment]
Close this invitation due to no response in a long time.

@yanboshu If you are still willing to write this blog, please submit a new issue and refer to this one.
