### ISSUE TITLE
bug: fix README.md

### ISSUE THREAD

**Issue by priyankarpal** [wechaty/docusaurus#1516]
In the README.md file images not showing. Please fix them.

![image](https://user-images.githubusercontent.com/88102392/229565459-40779fba-e963-4463-9fd4-88b92c630a2f.png)

**Comment by huan** [comment]
Thanks for pointing this out!

I'd like to accept a PR to fix them.

**Comment by priyankarpal** [comment]
> Thanks for pointing this out!
> 
> I'd like to accept a PR to fix them.

should I work on it?

**Comment by huan** [comment]
Sure, you are more than welcome to work on it!

**Comment by sujay2306** [comment]
@huan can i work on this if this is still open

**Comment by huan** [comment]
@sujay2306 Yes, you are more than welcome to work on it.

And yes, it's open.

**Comment by sujay2306** [comment]
@huan  https://sourcerer.io/ is down seems to me not working from which images are being fetched

**Comment by sujay2306** [comment]
<a href="https://github.com/wechaty/docusaurus/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=wechaty/docusaurus" />
</a>

instead of https://sourcerer.io  can I add this in readme ?

**Comment by sujay2306** [comment]
https://github.com/wechaty/docusaurus/pull/1521
@huan  can you please review
