### ISSUE TITLE
Invite chenjijie to write a blog of his repo used by wechaty

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#152]
@jijiechen is the author of https://github.com/jijiechen/dotnetclub-chaty

He is a senior consultant of Red Hat Software Open Innovation Lab, evangelist of .NET Core, agile software development and DevOps practitioner. 

He has been involved in the translation of ".NET Performance Optimization" and has published a large number of technical articles.

I would like to invite him to write about his repo: [dotnetclub-chaty](https://github.com/jijiechen/dotnetclub-chaty). He has published here: [dotnet club 借助 WeChaty 沉淀深度技术对话](https://blog.jijiechen.com/post/dotnet-club-use-wechaty-to-useful-wechat-chat-history/)

Looking forward for your fantastic article!

Cheers!

**Comment by huan** [comment]
Wow, it's a wonderful project!

Looking forward to reading the blog from @jijiechen !

**Comment by jijiechen** [comment]
I'll be working on it this evening. Thank you for the invitation.
