### ISSUE TITLE
the i18n url should be `/docs/zh/` instead of `/zh/docs` because the `/docs` is the docusarus root path.

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#1522]
@hcfw007 Could you please help us to send a PR to change it?

Thanks!

**Comment by hcfw007** [comment]
Why it should be /doc/zh? Other part of the website could also be muti-localed, although not yet

**Comment by hcfw007** [comment]
Take the home page as example. If we make a Chinese version of it, the url should be https://wechaty.js.org/zh

Afterall i18n should be a function of the whole website, not just for docs.

**Comment by huan** [comment]
After thinking for a while, I would like to agree with you.

Thank you very much for the explanation, appreciate it!
