### ISSUE TITLE
invite @fanazhe to write a new blog to introduce using wechaty to monitor wechat official account

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#19]
@fanazhe using wechaty to monitor wechat official acount, including posting time, content and content analysis.

**Comment by huan** [comment]
Fantastic!

BTW: if we want to do more, i.e. get the view number of an article, then we will miss PuppetAndroid more.

**Comment by huan** [comment]
Hello @fanazhe, what's your plan for this blog? I'm looking forward to it!

**Comment by huan** [comment]
Close this issue due to no response for a long time.

@fanazhe Please feel free to submit a new issue and refer to this one if you still like to write the article. Thanks.
