### ISSUE TITLE
Fix the problems of two blog post

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#191]
1. https://blog.chatie.io/wechaty-recruit-chatbot/
1. https://blog.chatie.io/microsoft-ai-global-training-camp-ends-in-beijing/

- [ ] leak of author profile
- [ ] author should be an individual
- [ ] improve the content quality
- [ ] add a teaser image to the post
- [ ] to be added...

**Comment by lijiarui** [comment]
hmm...

Page Not Found
Sorry, but the page you were trying to view does not exist — perhaps you can try searching for it below.

So I close this issue.

**Comment by huan** [comment]
Yes, they have already been deleted.
