### ISSUE TITLE
Invite @cubesky to share his experience for setting up the `matrix-appservice-wechaty` for [Matrix]

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#194]
See: https://github.com/wechaty/matrix-appservice-wechaty/issues/25#issuecomment-591762056

CC: @ericmigi

**Comment by cubesky** [comment]
https://liyin.date/2020/03/01/matrix-wechat-bridge/
You can just copy article to your blog and give a link to this url.

**Comment by huan** [comment]
Thanks for writing this great blog article, it's clear, well written and I believe it will be very helpful for the new users.

I can cross-post your blog to chatie blog, however, it would be best if you can send a pull request to this repo by yourself because you can fully control the layout with the markdown, and also I'd like to recommend you to add your profile to our blog so that the blog post will look nicer.

Would you like to do it yourself? It would be great if so, and please let me know what you think.

**Comment by cubesky** [comment]
Ok, I can directly copy markdown source file to this repo beacuse my blog is rendered from markdown.

**Comment by huan** [comment]
Great!

Please also remember to add yourself to our author data file <https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml> and link your blog post to it by your GitHub username.

Thank you very much!

**Comment by cubesky** [comment]
I just create pull request, due to my fault, commit is divided into two. I think squash it when merging is great.

**Comment by huan** [comment]
Published at <https://blog.chatie.io/matrix-wechat-bridge/>

@cubesky Thank you very much for introducing the matrix bridge to our chatie blog readers! Your contribution is very valuable.

I have invited you to join the Chatie contributor team on GitHub, you can find it from <https://github.com/orgs/Chatie/>.

And I'd like to invite you to join our Wechaty Contributor Wechat group, if you'd like to join, please let me know by adding my WeChat 918999, or contact @lijiarui.

Thank you again for the sharing!
