### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#2]
https://github.com/wechaty/blog.wechaty.io/commit/0b285641020e1406b1a1e62d45c8b19761ca07ca

_vedio_ should be **video**

And, this file is not necessary, if you write inline CSS in your posts.

**Comment by lijiarui** [comment]
I'm trying not to use CSS in my posts, it's not a good way ...

I think use file is the better way but failed..

**Comment by huan** [comment]
Thanks @cranialrectosis for fixing this.
