### ISSUE TITLE
[Plan] To move `chatie/blog` to `wechaty/wechaty.github.io`

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#204]
After that, the `blog.chatie.io` site will become the `wechaty.github.io`, which I believe is more fit for the content of this blog.

And also, because of the flexibility of the Jekyll system on GitHub Pages, we can make a portal website for Wechaty based on the current contents.

Please feel free to leave comments for future discussions if you have any good ideas or different opinions.

Thank you very much.

### To-do List

- [x] Fix the links in <https://github.com/wechaty/wechaty/wiki/Contributors>
- [ ] Setup blog.chatie.io to show a warning page with redirect link (?) after moving.

**Comment by huan** [comment]
Any comments? @lijiarui

**Comment by lijiarui** [comment]
Good idea~ I agree with this

**Comment by huan** [comment]
Done.

Link to https://github.com/wechaty/PMC/issues/3
