### ISSUE TITLE
[the "monster" demo] -- dead link in wechaty wiki contributor page  

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#223]
> the "monster" demo -- a one-stop wechaty demo that includes everything useful for people to get an easier start.

![image](https://user-images.githubusercontent.com/6419514/79070848-d41c7080-7d0a-11ea-8852-fa5c1cb3d8b0.png)

This is a dead link. We need to fix this. 

@suntong Could you help to fix this since this is your contribution. Thanks!

**Comment by suntong** [comment]
@lijiarui where is this dead link? All that I get from the above is a link to an image, which make it hard for me to figure out where the problem is. thx.

**Comment by lijiarui** [comment]
@suntong Thanks for the reply.

This page: https://github.com/wechaty/wechaty/wiki/Contributors

And you can scroll the screen to find your link.

**Comment by suntong** [comment]
Ah, Thanks for the link. Fixed now. 
please close.

**Comment by lijiarui** [comment]
Good Job！

Thanks
