### ISSUE TITLE
New Article: Build ChatBot with TensorFlow + Docker + Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#23]
https://github.com/Chatie/wechaty/issues/147#issuecomment-298321201

> I am currently learning TensorFlow. If everything is fine, I am considering to write an article about chatbot and TensorFlow. If possible, using TensorFlow (cuda) within Docker can be mentioned. However, it is also too specific rather than general. And it will take me a long period of time.

@imWildCat is studying Machine Learning Course now and planing to publish the article before July. let's looking forward for his second article about ML + Docker + Wechaty!

**Comment by huan** [comment]
@imWildCat Hi, how about the progress of your ML work? Hope you could publish the blog soon!

**Comment by MikeChongCan** [comment]
![snipaste_20170604_203211](https://cloud.githubusercontent.com/assets/2396817/26761583/02c1f25c-4965-11e7-9938-3adc4e632f27.png)

My course about Chatbot was released yesterday. It is based on Keras with a backend of Tensorflow or Theano. Hopefully I would implement a very basic Chatbot with Keras recently. It is likely that it can only interact with English contents.

**Comment by huan** [comment]
Awesome! I think English only will not be a problem, because we are focusing on the ML + Docker + Wechaty instead of Chinese/English.
