### ISSUE TITLE
Can Chatie inviteS friend with tag？

### ISSUE THREAD

**Issue by ghost** [wechaty/docusaurus#24]
we are Wilddog  Teachnology。when we use Chatie we found Chatie add new friends without wechat tag，and Chatie API do not support。 so i want to ask CAN CHATIE INVITE FRIENDS WITH TAG?

**Comment by huan** [comment]
Thanks for using Chatie.

Please submit Wechaty related issue to https://github.com/chatie/wechaty/issues

Here is Chatie Blog for publishing blog articles only.

And short answer for your question: No, because web wechat can not do that, so did Wechaty.
