### ISSUE TITLE
Write a blog about Azure show about wechaty

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#259]
- bilibili: https://www.bilibili.com/video/BV1vQ4y1A7W2
- WeChat Official article: https://mp.weixin.qq.com/s/szB4YSEAJZxDLSNZr-_3Sw

**Comment by huan** [comment]
Close this issue in favor of:

- [Azure Show - 如何用 QnAMaker.ai 构建一个投融资聊天机器人](https://wechaty.github.io/2020/05/19/qnamaker-juzi-bot-for-investors-rui/)
- [Azure Show - Wechaty 开源故事](https://wechaty.github.io/2020/05/19/open-source-wechaty-huan-2020/)
