### ISSUE TITLE
Publish the blog/news for our Plugin Publishing Event

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#264]
Link to https://github.com/wechaty/PMC/issues/10

Video Playback: <https://youtu.be/tfGZXoe_aA4>

**Comment by huan** [comment]
ping @rickyyin98 @lijiarui

**Comment by windmemory** [comment]
ping @rickyyin98 @lijiarui

**Comment by huan** [comment]
@rickyyin98 When could we publish our plugin meeting blog?

Please pay attention to https://github.com/wechaty/wechaty.github.io/issues/352 to embed the YouTube video URL in the right way, and make sure we embed all the meeting photos in the post.

Thank you very much.
