### ISSUE TITLE
Common pitfalls

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#298]
1. Should create a profile under author.yml when first commit a blog. #353
1. ~~The author value in the post header should be the key in `author.yml`~~ #350
    - Huan(202011) should be the filename in the `_developers/` folder
1. Should add teaser for the blog #351
1. The image in the blog should store in the repo instead of using an image URL outside of the blog domain.
1. The image should store under `/assets/2020/XXX/XXX.png&jpg`. Remember not just create file under the 2020 folder, you should create a new folder under 2020.
1. A correct filename patter, see #325 
1. author.yml format, see #349
1. A correct blog header, see #355
1. `_post/SLUG.md`: SLUG should be at lease three slugs:
    - valid: `a-b-c.md`
    - invalid: `a.md`, `a-b.md`
1. Blog post author should be all lowercase #585

**Comment by huan** [comment]
Thank you very much for a summary of those problems together!

We should add more unit tests to check those common pitfalls and make those problems to be clear for our Pull Request submitters.

**Comment by huan** [comment]
After a hard work on this issue, we finally have unit tests guard all of the above common pitfalls!

If any of the above pitfalls is met, the CI will not turn green, and the error message should be clear enough for developers for troubleshooting.

Cheers!
