### ISSUE TITLE
Publish a blog for Summer of Code 2020

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#303]
Related to: https://github.com/wechaty/summer-of-code/issues/3

### Outlines

1. Background of Summer of Code 2020 and Wechaty Community
1. SoC slides for Wechaqty Community (pdf with viewer.js)
1. Project list, with introduction
    1. Mentor list, with introduction
    1. SoC official student developer list, with introduction
    1. Non-official(not being selected by the SoC, but interested) student developer list, with introduction
1. The SoC timeline & Wechaty Community Plan, with DDL
1. Summary

**Comment by rickyyin98** [comment]
https://github.com/wechaty/wechaty.github.io/pull/347

Based the outlines, fill all topics and add some new things

- 关于暑期2020
- Wechaty 与暑期2020
- Wechaty 暑期2020宣讲会
- Wechaty 项目列表
- SoC破冰会会议纪实
- 暑期2020 开发计划
- 欢迎正在阅读的你参与其中

**Comment by huan** [comment]
Thank you very much for this great blog post!

It's a milestone for our Wechaty Summer of Code projects. Appreciate all your efforts for managing and pushing all those projects moving forward!

BTW: Let's add this blog post to our https://github.com/wechaty/summer-of-code README after it published!
