### ISSUE TITLE
CI check error

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#325]
Our writing style is:

Keep all filenames & url as lowercase, and use - to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`

But ` assets/2020/meeting-notes/07.05.head-picture.jpg` can make ci green as https://github.com/wechaty/wechaty.github.io/pull/321 show.

So we should add a rule for ci to check this kind of situation.

**Comment by huan** [comment]
Thanks for the recording! Will add more check into our CI tests later.

**Comment by huan** [comment]
Merge to #298
