### ISSUE TITLE
YouTube Video embed code not right

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#352]
The embed video in our blog post can not be played at all.

Related to: https://github.com/wechaty/wechaty.github.io/blob/master/_posts/2020-07-20-wechaty-soc-kick-off-meeting.md

The following embed code is not right:

```html
<iframe src="https://youtu.be/fMFzCexnDsY " width="560" height="315" frameborder="0" allowfullscreen="" style=" position: absolute; top:0; left:0; width:100%; height:100%; "></iframe>
```html

The following embed code is right:

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/39TteTtCkd4" frameborder="0" allowfullscreen="" style=" position: absolute; top:0; left:0; width:100%; height:100%; "></iframe>
```

Please pay attention to the following diffs:

```diff
-  src="https://youtu.be/fMFzCexnDsY "
+ src="https://www.youtube.com/embed/39TteTtCkd4"

**Comment by huan** [comment]
And I'd like to suggest that we should add more screenshots for the meeting (photos) in our blog post, to increase the readability and make the readers feel better.

**Comment by rickyyin98** [comment]
Done

**Comment by huan** [comment]
That's great, thank you very much for the fixing!
