### ISSUE TITLE
Invite @dcsan to write a blog article to record the second Chatie event in Shanghai

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#40]
Today we had a Chatie Contributor dinner at Jingan, Shanghai.

@dcsan, who is the founder of rikai and has developed chatbot products since 2014. He is very experienced with chatbot. Rikai has a lot of TOB chatbot businesses like ticket bot, meeting bot, FAQ bot for many big companies. Also, Rikai has a teacher bot to teach people to learn English using chatbot with wechat OA account and wechat group. I visited his office and meet all of his fantastic team members, I really like them. Also, we are going to work together to do some wechaty wrappers for each of our projects.

I'd like to invite him to write the blog post to introduce the contributor of our lunch today, and share his opinions about the chatbot and relevant NLP things that we had talked about today.

Thanks, dcsan!

**Comment by dcsan** [comment]
great meeting everyone and finding other Chatie users in shanghai! I'll put some comments for a  post down asap!

**Comment by hczhcz** [comment]
@dcsan Great meeting & looking forward to your blog post!
Also, thanks @ax4 for inviting me to this event!

**Comment by huan** [comment]
Ping @dcsan , looking forward to your blog post! :)

**Comment by huan** [comment]
Thanks, DC!

See #45 #44

**Comment by dcsan** [comment]
TODO @dcsan > Link to `join-us` page / QR code
https://github.com/Chatie/wechaty#join-us

**Comment by lijiarui** [comment]
Thanks @dcsan and I will close the issue.
