### ISSUE TITLE
Add best practice

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#422]
fill in some content but not the best at this period, should keep iterating...
https://docs.chatie.io/v/zh/best-practice

# 最佳实践

https://docs.chatie.io/v/zh/best-practice

## 2. 机器人启动方法

see https://github.com/Chatie/wechaty/issues/1478#issuecomment-405188478

```ts
import { PuppetPadchat } from 'wechaty-puppet-padchat'
const puppet = new PuppetPadchat()
const bot = new Wechaty({ puppet })
```

## 7. 代码示例

**Comment by huan** [comment]
Close this issue for housekeeping.

Please feel free to re-open it as need.
