### ISSUE TITLE
add send url docs 

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#424]
see https://docs.chatie.io/v/zh/faq#url-message

Should add to 
- Contact.say()
- Room.say()
- Message.say()

Both add to Chinese version and English version

**Comment by huan** [comment]
Please finish this task, or close it if you think it should.

Thank you very much.

**Comment by lijiarui** [comment]
Will check this later.

**Comment by huan** [comment]
Close this issue for housekeeping: It's delayed too long.

Please feel free to re-open it as you need.
