### ISSUE TITLE
错误的描述：非Web版本解决方案不是“我们”提供的

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#425]
> {% hint style="success" %} 解决方案： 我们提供了非web 版本解决方案，点击购买token , 更多技术细节查看 wechaty-puppet-padchat {% endhint %}

请将此类描述，统一查找后，改为明确的“第三方提供”类型表述。

因为我们（在这里，代表Chatie），并没有提供此类解决方案。提供具体解决方案的是第三方。

**Comment by lijiarui** [comment]
done
