### ISSUE TITLE
New website published at https://wechaty.js.org

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#440]
We have merged `wechaty.github.io` to `wechaty.js.org` this week.

Now, we have blog posts via Jekyll and docs via Docusaurus and publish them together via Github Pages, and we have both blogs & docs together under the great <https://wechaty.js.org> domain name!

Features:

1. [News](https://wechaty.js.org/news/) & [Blogs](https://wechaty.js.org/blog) from our community!
1. [Docs](https://wechaty.js.org/docs/) for Wechaty!
1. [Online QR Code Image Generator](https://wechaty.js.org/qrcode/) for convenience!

Please feel free to comment on this issue if you have any good suggestions for our website, and PR is welcome!

**Comment by huan** [comment]
Done.

**Comment by zhuyujie068** [comment]
能否增加一个中文文档？

**Comment by xhl2010** [comment]
可以建一个中文社区吗？

**Comment by huan** [comment]
@xhl2010 Yes, we have a WeChat room in Chinese only.

You can send `中文` to our Friday.BOT on WeChat to get an invitation.

**Comment by suntong** [comment]
Any search on https://wechaty.js.org/ will result in _"Page Not Found"_ error --

`We could not find what you were looking for.`

which has a line on the top "We are looking to revamp our website, please comment on this issue", pointing to here. 

Shall I keep the discussion here or open a new issue for search failures?

**Comment by huan** [comment]
@suntong Yes, please file a new issue for search failures.

We have some problem in the search part of our website, and we need to fix it.

**Comment by phasmid42** [comment]
Typo:
https://wechaty.js.org/docs/explainations/

explainations --> explanations

**Comment by huan** [comment]
@pallas42 good catch, thank you very much!
