### ISSUE TITLE
webfont link & umd-popper link are broken in china

### ISSUE THREAD

**Issue by sidny** [wechaty/docusaurus#446]
https://fonts.font.im/css?family=Lora
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js 

这两个链接貌似被墙了，需要更换链接或者删除

**Comment by huan** [comment]
Thanks for pointing those two hard-to-visit-in-china links for us!

I have replaced them to the loli.net, which was recommended by @crossly before, it should work after the website has been re-deployed.

Please let me know if this problem has been solved in your environment, thanks!

**Comment by huan** [comment]
I think this problem has been solved. Thank you very much for the report!
