### ISSUE TITLE
Adjust the video & PPT size

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#458]
https://wechaty.js.org/2020/08/13/python-wechaty-meme-bot-mid-term/

![image](https://user-images.githubusercontent.com/6419514/90336091-154fc480-e00c-11ea-8d40-fa504d827918.png)

You can refer my blog video link here:
https://wechaty.js.org/2020/05/19/qnamaker-juzi-bot-for-investors-rui/

Thanks!

**Comment by MrZilinXiao** [comment]
Sorry for the inconvenience! I have altered bilibili iframe into links, and used Youtube iframe. The local test seems okay: 
![image](https://user-images.githubusercontent.com/42504790/90338351-abd7b200-e01b-11ea-9cbb-e5b63b960900.png)

https://github.com/wechaty/wechaty.js.org/pull/462

**Comment by lijiarui** [comment]
merge in #462
