### ISSUE TITLE
YouKu video does not show

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#493]
See: https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/

Could you please have a check on it? @univerone 

Thanks!

Update: it seems that we should convert all `http` protocol to `https` to prevent this kind of situation:

> Mixed Content: The page at 'https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/' was loaded over HTTPS, but requested an insecure frame 'http://player.youku.com/embed/XMjQ3NjUxMjAwOA=='. This request has been blocked; the content must be served over HTTPS.

**Comment by univerone** [comment]
Thanks for your notation! I'll fix it!

**Comment by huan** [comment]
Awesome, I'm looking forward to the fix!

One more thing: the quality of the YouKu video example link that in your post is kind of low, it would be better if you could replace it with a higher quality video. Just FYI.

**Comment by univerone** [comment]
> Awesome, I'm looking forward to the fix!
> 
> One more thing: the quality of the YouKu video example link that in your post is kind of low, it would be better if you could replace it with a higher quality video. Just FYI.

It seems like youku iframe only support high quality version of short videos within 10mins(In the website, only VIP users can watch 1080p version)， should I replace this link with a wechaty unrelated video？

**Comment by huan** [comment]
No, please use Wechaty related video.

The resolution is ok, however the content of that video I believe can be changed to    another one and let's see if it could be better.
