### ISSUE TITLE
invite @sinned Dennis Yang to write a blog for introducing how to integrate Wechaty with ChatBot Analytics Service: DashBot.io

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#52]
Dennis Yang is the co-founder & CPO of DashBot.io, lived in the US. Dashbot is a bot analytics platform that enables publishers and developers to increase engagement, user acquisition, and retention through actionable data and tools.

Last year I met with Dennis at Silicon Valley and had a great talk. After that, we decided to add Wechaty support on DashBot, which will enable Wechat ChatBot to get Analytics Service powered by DashBot.io. 

After some months of work and with the help of @lijiarui, this feature had online today and I'd like to invite @sinned Dennis to write a blog post to introduce how to enable Wechaty ChatBot with Message Analytics Service: Integrating with DashBot.io.

Thank you, Dennis!

**Comment by huan** [comment]
ping @sinned

**Comment by sinned** [comment]
Hello! Yes.. this has been waiting WAY too long. My apologies. I am traveling right now, but will take a look at this next week. Thanks for the reminder!!

**Comment by huan** [comment]
Great, and have a nice weekend!

**Comment by huan** [comment]
I'm going to close this issue because it had delayed too long.

Please let me know by leaving a reply if you want to write it and I would like to reopen it for you.
