### ISSUE TITLE
invite @xinbenlv to write a blog post about the new `hot-import` style listeners of Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#56]
We are recently upgrading Wechaty to the branding new _v0.11.x_ version, which supports register listeners by a module file.

Through this way, Wechaty can not only load the module file and use the exported function as the listener, but also auto reload the module code when the module file is changed, which is called a **Hot Module Replacement** Technic in WebPack, from WebPack Concepts - https://webpack.js.org/concepts/hot-module-replacement/

@xinbenlv had just sent a Pull Request to Wechaty, added an example to show how to use this kind of listeners. I'd like to invite him to also write a blog post to share this technic to the Wechaty Community, which I believe will help other developers to save lots of time when developing.

Thank you @xinbenlv, looking forward to your blog post!

**Comment by huan** [comment]
ping @xinbenlv: do you have time to finish this blog post recently? this article would really be helpful for the new Wechaty users who need to modify the listeners frequently!

**Comment by huan** [comment]
ping @xinbenlv

**Comment by xinbenlv** [comment]
HotImport was not very stable due to the sticky situation (maybe because of NodeJs caching)? I end up stop using HotImport... I guess I am not the best person to write this blog post any more... Can someone else take it? For example, the author of HotImport I remember was a group member?

**Comment by huan** [comment]
Hmm... I'm that author: https://github.com/zixia/hot-import/ 

In my experience, `hot-import` works without any problem and it was also be integrated with the Wechaty already. 

See:

https://github.com/Chatie/wechaty/blob/7aaa42b6211bb0527eb51dbab15ef512dac819d4/src/wechaty.ts#L421-L425

Would you like to test it again? If you have any problem, please feel free to file an issue to it and I'll be able to go to look at it and fix it for you.

**Comment by huan** [comment]
Close this issue because it seems that @xinbenlv will not write it.

Hope there will be someone write this blog in the future.
