### ISSUE TITLE
write a blog for  wehcaty-puppet-whatsapp  publishment

### ISSUE THREAD

**Issue by univerone** [wechaty/docusaurus#600]

**Comment by huan** [comment]
Merge to #588

**Comment by huan** [comment]
Ping @univerone 

Could we make a plan for publishing this great blog announcement so that more developers could get to know we start supporting the WhatsApp?

**Comment by univerone** [comment]
> Ping @univerone 
> 
> Could we make a plan for publishing this great blog announcement so that more developers could get to know we start supporting the WhatsApp?

 
I'll get started tomorrow and publish it within next week.

**Comment by huan** [comment]
That's awesome!

Thank you very much and looking forward to reading your great post!

**Comment by huan** [comment]
kindly ping @univerone  , and happy Chinese New Year!
