### ISSUE TITLE
cloning this project is toooooooooooo slow

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/docusaurus#601]
When we fork & clone this project, this is a long time waiting for clone ending. Is there an official solution for us to speed up cloning or reduce the size of this project ?

**Comment by huan** [comment]
Yes, there's a very good solution for speed up cloning this repo and I always use it!

### Official Solution

Use a server that is not in China.

### Other Potential Solutions

1. Use Git LFS: it requires the developer to do more and very easy to make mistakes
1. Separate the `docs` and `jekyll`: the `docs` will be small, but the `jekyll` is still very large
1. To be added: please feel free to add more potential solutions by commenting on this issue!
