### ISSUE TITLE
Could you invite me to Wechaty contributor room?

### ISSUE THREAD

**Issue by hywhuangyuwei** [wechaty/docusaurus#625]
The Juzi.BOT says that I need to be in that room so that I could get a token.
But I received no invitations on Wechat yet.

My wechat ID: hywhuangyuwei

**Comment by huan** [comment]
Please provide the pull requests link so that we can check it for you, thanks!

**Comment by hywhuangyuwei** [comment]
> Please provide the pull requests link so that we can check it for you, thanks!

https://github.com/wechaty/wechaty.js.org/pull/554

**Comment by huan** [comment]
Merge to #554 because I have replied over there.
