### ISSUE TITLE
blog not show problem for .NET Wechaty post

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#637]
related #633 

I believe the problem might be related to the file name `_post/2020-12-2-.NET Wechaty 使用介绍.md`

1. the post filename should use English. 
2. the date prefix should be `2020-12-02-`

**Comment by Jesn** [comment]
had update blog title as  `2020-12-31-csharp wechaty getting start.md`    #638

**Comment by huan** [comment]
There's another problem with your PR which cause the blog post can not be shown: our blog post file should be put in the `jekyll/_posts` directory, but where you put your post in is `_posts`.

I'll help you to move the post from `_posts/` to `jekyll/_posts/`

**Comment by huan** [comment]
I believe I have fixed most of the problems in our .NET Wechaty blog post, please check it out at <https://wechaty.js.org/2020/12/31/csharp-wechaty-getting-start/>

**Comment by huan** [comment]
Merge to #298
