### ISSUE TITLE
how to get a one-year free token by submit an "MVP“？I hava already finish an mvp that published on the github .

### ISSUE THREAD

**Issue by CashunterXie** [wechaty/docusaurus#676]
how to get a one-year free token by submit an "MVP“？I hava already finish an mvp that published on the github .

**Comment by huan** [comment]
To get a long-term (one-year) free token, I believe you need to join the Contributor Program first.

See: https://wechaty.js.org/docs/contributor-program/

**Comment by CashunterXie** [comment]
> To get a long-term (one-year) free token, I believe you need to join the Contributor Program first.
> 
> See: https://wechaty.js.org/docs/contributor-program/

After reading the link, I cannot really understand how to join the  contributor program. Could you please tell me how to do ? to post a blog?

**Comment by huan** [comment]
Yes, post a blog successfully will make you a contributor! :)

**Comment by huan** [comment]
I hope my reply has ansewred your question. I Will close this issue and please feel free to ask at our Gitter Network <https://gitter.im/wechaty/wechaty> if you have any questions.
