### ISSUE TITLE
Using Google Tag Manager for Tracking

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#732]
I invested a lot of time to study, today after watch [Google Tag Manager vs. the Global Site Tag (gtag.js) - Similarities and Differences (with lessons)](https://www.youtube.com/watch?v=tKq_GEGnK2o) I decided to use it for our website.

It seems that the Docusaurus is not supported officially, so the [Docusaurus plugin for Google Tag Manager](https://github.com/ionic-team/docusaurus-plugin-tag-manager) from the ionic team is what I need for. (another alternate is [This is a Google Tag Manager (GTM) plugin for docusaurus v2](https://github.com/LukasGentele/docusaurus-gtm-plugin))

Jekyll GTM support: [Jekyll Google Tag Manager Plugin](https://github.com/t-richards/jekyll-google-tag-manager)

## Resources

- [11 Reasons Why You Should Use Google Tag Manager](https://www.analyticsmania.com/post/reasons-why-you-should-use-google-tag-manager/#event-tracking)
- [Google Tag Manager Button Click Tracking for Google Analytics, Facebook, and AdWords](https://www.youtube.com/watch?v=r87A-Ql2czg)

**Comment by huan** [comment]
Docusaurus switched to use Google Tag Manager now.

**Comment by huan** [comment]
Jekyll switched to use Google Tag Manager now.

**Comment by iamrajiv** [comment]
@huan I think this issue can be close because Google Tag Manager for both Docusaurus and Jekyll has been implemented.

**Comment by huan** [comment]
@iamrajiv Thanks for the reminding! Close it.
