### ISSUE TITLE
Invite @padlocal to write a blog post for our meetup in Beijing last week

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#733]
Last week, @padlocal, Haoda, who is the creator of the [Wechaty Puppet Service PadLocal](https://wechaty.js.org/docs/puppet-services/), come to Beijing and we have a great time for coffee and lunch.

We have discussed the WXWork, gRPC/Proto-buffer, and the future workshops for making our Wechaty Ecosystem better and helping more developers from our community.

Looking forward to reading your post, @padlocal Haoda!

**Comment by padlocal** [comment]
Ok, I am preparing for the post.

**Comment by huan** [comment]
Published at https://wechaty.js.org/2021/04/05/wechaty-contributor-meetup/ with #746

Thank you very much @padlocal !
