### ISSUE TITLE
Error running Vorpal with Wechaty example

### ISSUE THREAD

**Issue by sbis04** [wechaty/docusaurus#771]
I tried to run the example code for **Vorpal with Wechaty** given here: https://wechaty.js.org/docs/tutorials/using-vorpal-with-wechaty#usage

But I am facing an error in importing **`vorpal-hacker-news`**:

<img width="568" alt="Screenshot 2021-04-24 at 8 06 24 AM" src="https://user-images.githubusercontent.com/43280874/115944857-08a63900-a4d6-11eb-94f0-215e0ea54944.png">

The test project using which I was trying out is present here: https://github.com/sbis04/vorpal-wechaty-test

Please let me know how can I fix this error.

**Comment by huan** [comment]
The reason for this error is that the `vorpal-hacker-news` has not support the TypeScript typings.

So a workaround is to use `require` instead of `import`:

```diff
- import hackerNews from 'vorpal-hacker-news'
+ const hackerNews = require('vorpal-hacker-news')
```

**Comment by sbis04** [comment]
Thanks! It solved the issue.

**Comment by huan** [comment]
You are welcome.

Glad to know that you have solved your problem!
