### ISSUE TITLE
Unexpected character ~ in "{{>member-index-list~}}" in 2017-09-20-add-wechaty-jsdoc.md

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#80]
> Liquid Warning: Liquid syntax error (line 141): Unexpected character ~ in "{{>member-index-list~}}" in /Users/zixia/chatie/blog/_posts/2017-09-20-add-wechaty-jsdoc.md

**Comment by huan** [comment]
Did you fix this bug?

Please let me know if there's any problem, or close this issue if it had already been fixed. thx.

**Comment by lijiarui** [comment]
I've no idea how to fix and maybe I will change blog template in the following 2 months, so I will close this issue.
