### ISSUE TITLE
Images not appearing - Vorpal tutorial page

### ISSUE THREAD

**Issue by sbis04** [wechaty/docusaurus#801]
I noticed on the deployed version of the Wechaty docs some of the images are not appearing on the "Using Vorpal with Wechaty" tutorial page. But when I compile and run it locally, it looks perfectly fine. I was wondering what is causing the issue.

### On deployed Wechaty docs:
![Screenshot 2021-05-03 at 8 39 37 AM](https://user-images.githubusercontent.com/43280874/116838347-b0fd8100-abeb-11eb-8f54-f22d04271d02.png)

### Locally:
![Screenshot 2021-05-03 at 8 39 51 AM](https://user-images.githubusercontent.com/43280874/116838375-c4a8e780-abeb-11eb-8b60-d540440e2f1f.png)

Is it this HTML format causing it?

```html
<p align="left">
  <img src="../../static/img/docs/tutorials/using-vorpal-with-wechaty/vorpal-hn-help.png" alt="Vorpal help" />
</p>
```

**Comment by huan** [comment]
Yes, please always using Markdown with our docs, and it should be **enforced** because the docusaurus can check it for us.

HTML should be avoided as possible as we can.
