### ISSUE TITLE
Invite @TingYinHelen to write a blog on Google Dev Festival

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#82]
@TingYinHelen share her thoughts about wechaty and taught a lot of developers on Google Dev Festival in Chengdu.

I'd like to invite her to post a blog post on chatie blog to share her experience on Google DevFestival.

Thanks! @TingYinHelen

**Comment by huan** [comment]
Great, looking forward to the new article, thank you @TingYinHelen !

**Comment by lijiarui** [comment]
ping @TingYinHelen ：）

**Comment by lijiarui** [comment]
ping @TingYinHelen

**Comment by lijiarui** [comment]
I will close this issue due to long time no reply. Feel free to contact me if you want to write this again.
