### ISSUE TITLE
Invite @phoenixgao to write a blog about wechat bot thoughs

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#84]
@phoenixgao is a PHP developer in Shanghai, who is interested in WeChat bot.

Today he talked a lot of interesting thoughts about the upcoming bot API based on iPad.

I'd like to invite him to talk about the existing WeChat bot and what should he suggest to do before we push out a charging scheme, for example, data monitor, status monitor, etc.

We are looking forward to this awesome articles from @phoenixgao, cheers!

**Comment by lijiarui** [comment]
ping @phoenixgao : do you have time to finish this blog post recently?  We are looking forward for your blog！

**Comment by phoenixgao** [comment]
@lijiarui Sorry.
I had been doing some research about various wechat bots a while ago, but you see in this field things really goes fast, especially wechaty, it grows so fast, like padchat puppet etc, whatever comments I wrote down they become invalid soon :p , so I'd like to wait a bit for more features come out. Also I've been a bit busy with personal stuff recently, so probably I can not finish this blog soon.

But if you don't mind, I'd like keep this ticket open.

**Comment by lijiarui** [comment]
@phoenixgao glad to hear from you again and looking forward to your blog post this month!

Thanks!

**Comment by lijiarui** [comment]
ping @phoenixgao , We are still waiting for your blog :)

**Comment by lijiarui** [comment]
I will close this issue due to long time no reply. Feel free to contact me if you want to write this again.
