### ISSUE TITLE
Invite @chatrbot to publish his new puppet: simplepad

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#852]
Today, we have received a issue https://github.com/wechaty/wechaty/issues/1930#issuecomment-840281497 that asks about the puppet developing, which we get to know that @chatrbot is planning to build a new Wechaty puppet named simplepad, repo: https://github.com/chatrbot/wechaty-puppet-simplepad

It looks great, and after a great conversation between chatrbot and me, we decide to prepare to publish a blog post for announcing the simplepad new puppet to our community.

Looking forward to reading your simplepad puppet announcing blog post, @chatrbot!

**Comment by lijiarui** [comment]
https://wechaty.js.org/2021/06/17/puppet-simplepad-hello/
