### ISSUE TITLE
Review comments for the migration Wechaty v0.14 to v0.16 blog article

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#88]
For <https://blog.chatie.io/porting-code-from-puppeteer-to-padchat-en/>

- [x] Subject: please name it more explicit for the migration. like 
  - [x] **Migrating/Upgrading Wechaty v0.14 to v0.18 Guide  - From Puppeteer To Padchat**, 
  - [x] because we will publish v0.18(BETA) soon.
- [x] Picture
  - [x] please use English title in the English version. Currently, there are Chinese in the English version, and very hard to differentiate when we reading the blog home page.
  - [x] Add **v0.14** near _Puppeteer_, and add **v0.18** near _Padchat_ to show the specific version and make it more clear.
- [ ] Topic: I'd like to suggest that you **split this article into four different articles(blogs)**, because there are four topics in this article and they are all big topics: 
  - [ ] 1. introducing the puppet system; 
  - [ ] 2. getting started with the puppet padchat; 
  - [ ] 3. linting is very useful; 
  - [ ] 4. breaking changes between versions. 
  - [x] If you agree with me, I'd like to suggest that we can invite @windmemory to join you.

Related to https://github.com/Chatie/wechaty/issues/1442

**Comment by huan** [comment]
Please leave your comments in the reply so that I could be able to know what you think and what the plan next, thanks.

**Comment by huan** [comment]
Please keep only one of 'migrating' and 'upgrading' in the title & url.

**Comment by lijiarui** [comment]
done the basic requirement, will spliting the article in future wiki works.
