### ISSUE TITLE
A blog to announce  web version of WeChat closed group interface

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#89]
Thanks to @Zhou-Bill pointing that Web version of WeChat closed group interface, issue here: https://github.com/Chatie/wechaty/issues/1441

I'd like to invite him to write a blog about his experience and any other thoughts he wants to write.

Thanks! Bill！

**Comment by lijiarui** [comment]
I will write this blog in this month.

**Comment by huan** [comment]
I'm going to close this issue because it had delayed too long.

Please let me know by leaving a reply if you want to write it and I would like to reopen it for you.
