### ISSUE TITLE
invite @kaffa to write a blog as a tutorial for windows users

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#91]
@kaffa shared his experience when use Wechaty under Windows at https://github.com/Chatie/wechaty-getting-started/issues/41

I'd like to invite @kaffa to share his experience on our Chatie Blog as a Windows User Tutorial, and that will be very valuable for the community.

Thanks @kaffa for accepting my invitation, will looking forward to your windows tutorial.

**Comment by huan** [comment]
Hello @kaffa, Just want to know when will you write this blog, could we expect it in this week?

**Comment by kaffa** [comment]
Hello @zixia, Because this needs a clean Windows 10, I reinstalled node and other dependencies yesterday. Now the post is done [here](https://kaffa.im/wechaty-installation-in-windows-10.html)

**Comment by huan** [comment]
I had just read your post, it is very easy to read and follow, which is great!

Could you please cross-post it to the blog.chatie.io, so that we can make it easier for the Wechaty developers?

**Comment by kaffa** [comment]
I have no ruby runtime or jekyll package in my computer, so I send a pr to the blog repos.

**Comment by huan** [comment]
Blog posted at <https://blog.chatie.io/wechaty-installation-in-windows-10/>

Thank you very much!
