### ISSUE TITLE
Invite @judaschrist to write a blog about Industry expert bot using wechaty

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#94]
@judaschrist is CTO of [小理智能](https://xiaoli.ai/) They are trying to use ai to discover the value of all information. They have some products like business intelligence bot and an efficiency reading tool called `小理简报`

These days, they are trying to combine wechaty and their powerful intelligent information API to provide vertical industry bot for developers.

So I'd like to invite him to write a blog about their industry expert bot, how can the bot help others, and how can a developer use wechaty & their API to make a fantastic industry bot!

Thanks, @judaschrist!

**Comment by judaschrist** [comment]
#98 I created a PR here, check it out!

**Comment by huan** [comment]
@judaschrist Welcome and thanks for writing the blog for the community!

**Comment by lijiarui** [comment]
Thanks for the blog!
